[global/wm]

include-file = $HOME/.config/polybar/colors.ini
include-file = $HOME/.config/polybar/modules.ini

[bar/dp-0]
monitor = DP-0

width = 99%
height = 32pt
radius = 4

offset-x = 0.5%
offset-y = 10

dpi = 100

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 3pt

border-size = 0pt

padding-left = 0
padding-right = 1

module-margin = 1

separator = ""
separator-foreground = ${colors.disabled}

font-0 = MartianMono Nerd Font:size=12;4
font-1 = MartianMono Nerd Font:size=16;4

modules-left = menu xworkspaces
modules-center = cpu gpu memory
modules-right = systray pulseaudio xkeyboard date powermenu

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

wm-restack = bspwm
;---------------------------------------------

[bar/hdmi-0]
monitor = HDMI-0

width = 99%
height = 30pt
radius = 4

offset-x = 0.5% 
offset-y = 10

dpi = 100

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 3pt

border-size = 0pt

padding-left = 0
padding-right = 1

module-margin = 1

separator = ""
separator-foreground = ${colors.disabled}

font-0 = MartianMono Nerd Font:size=12;3
font-1 = MartianMono Nerd Font:size=14;4

modules-left = menu xworkspaces
modules-center = cpu gpu memory
modules-right = pulseaudio xkeyboard date powermenu

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

wm-restack = bspwm
